provider:
  name: faas
  gateway: http://localhost:8080

functions:
  func_obese_heavy:
    lang: node
    handler: ./sample-functions/func_obese_heavy
    image: sample-functions/func_obese_heavy
    extras:
        cloudOnly: true
    build:
        extra-files:
            from: ./my_rig_config.json
            to: /home/app/function/my_rig_config.json
  func_super_heavy:
    lang: node
    handler: ./sample-functions/func_super_heavy
    image: sample-functions/func_super_heavy
    build:
        extra-files:
            from: ./my_rig_config.json
            to: /home/app/function/my_rig_config.json
  func_heavy:
    lang: node
    handler: ./sample-functions/func_heavy
    image: sample-functions/func_heavy
    build:
        extra-files:
            from: ./my_rig_config.json
            to: /home/app/function/my_rig_config.json
  func_light:
    lang: node
    handler: ./sample-functions/func_light
    image: sample-functions/func_light
    build:
        extra-files:
            from: ./my_rig_config.json
            to: /home/app/function/my_rig_config.json
