provider:
  name: faas
  gateway: http://localhost:8080

functions:
  func_obese_heavy:
    lang: node
    handler: ./sample-functions/func_obese_heavy
    image: sample-functions/func_obese_heavy
    extras:
        weight: 9007199254740991
        cloudOnly: true
    build:
        extra-files:
            from: ./my_rig_config.json
            to: /home/app/function/my_rig_config.json
  func_super_heavy:
    lang: node
    handler: ./sample-functions/func_super_heavy
    image: sample-functions/func_super_heavy
    extras:
        weight: 1000
    build:
        extra-files:
            from: ./my_rig_config.json
            to: /home/app/function/my_rig_config.json
  func_heavy:
    lang: node
    handler: ./sample-functions/func_heavy
    image: sample-functions/func_heavy
    extras:
        weight: 100
    build:
        extra-files:
            from: ./my_rig_config.json
            to: /home/app/function/my_rig_config.json
  func_light:
    lang: node
    handler: ./sample-functions/func_light
    image: sample-functions/func_light
    extras: 
        weight: 10
    build:
        extra-files:
            from: ./my_rig_config.json
            to: /home/app/function/my_rig_config.json
